services:
  workana-scraper:
    # Usar uma imagem já buildada (Docker Hub, GitHub Registry, etc.)
    image: your-registry/workana-scraper:latest
    # Ou se você fez push para Docker Hub:
    # image: seuusuario/workana-scraper:latest
    
    ports:
      - "8651:8651"
    environment:
      PYTHONUNBUFFERED: "1"
      WORKANA_EMAIL: "faelzim34@gmail.com" 
      WORKANA_PASSWORD: "202526.Wk"
    restart: unless-stopped
    
    # Sobrescrever o código se necessário (desenvolvimento)
    volumes:
      - ./worker.py:/app/worker.py:ro  # Read-only para segurança
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8651/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # Bem rápido já que a imagem está pronta
    
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"